name: frontend-branch

on:
  pull_request:
    branches:
      - master
    paths:
      - frontend/**
      - .github/workflows/frontend-branch.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Login to docker"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: "Build & Push image"
        run: |
          cd frontend
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend -t latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend
